### ISSUE TITLE
Versions >= 5.0.0 are not being released to anaconda.org

### ISSUE THREAD

**Issue by MattF-NSIDC** [conda-forge/gspread-feedstock#28]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Latest available version is 4.0.1:

https://anaconda.org/conda-forge/gspread/files

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by burnash** [comment]
Thank you for reporting this. I've just released 5.3.0. Could you please check if you're able to install it?
